awk 'FNR == 1 && NR!=1{next;}{print}' *_cm_artist_rank.csv > merged/merged_cm_artist_rank.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_facebook_likes.csv > merged/merged_facebook_likes.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_facebook_talks.csv > merged/merged_facebook-talks.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_genres.csv > merged/merged_genres.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_id.csv > merged/merged_id.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_instagram_followers.csv > merged/merged_instagram_followers.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_latest_album_release_date.csv > merged/merged_latest_album_relase_date.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_latest_album_upc.csv > merged/merged_latest_album_upc.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_name.csv > merged/merged_name.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_position.csv > merged/merged_position.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_soundcloud_followers.csv > merged/merged_soundcloud_followers.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_spotify_followers_to_listener_ratio.csv > merged/merged_spotify_followers_to_listener_ratio.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_spotify_followers.csv > merged/merged_followers.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_spotify_listeners_to_follower_ratio.csv > merged/merged_spotify_listeners_to_follower_ratio.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_spotify_monthly_listeners.csv > merged/merged_spotify_monthly_listeners.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_spotify_popularity.csv > merged/merged_spotify_popularity.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_spotify_where_people_listen.csv > merged/merged_spotify_where_people_listen.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_tiktok_followers.csv > merged/merged_tiktok_followers.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_tiktok_likes.csv > merged/merged_tiktok_likes.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_twitch_followers.csv > merged/merged_twitch_followers.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_twitch_monthly_viewer_hours.csv > merged/merged_twitch_monthly_viewer_hours.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_twitch_views.csv > merged/merged_twitch_views.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_twitch_weekly_viewer_hours.csv > merged/merged_twitch_weekly_viewer_hours.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_twitter_followers.csv > merged/merged_twitter_followers.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_twitter_retweets.csv > merged/merged_twitter_retweets.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_youtube_channel_views.csv > merged/merged_youtube_channel_views.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_youtube_daily_video_views.csv > merged/merged_youtube_daily_video_views.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_youtube_monthly_video_views.csv > merged/merged_youtube_monthly_video_views.csv &&
awk 'FNR == 1 && NR!=1{next;}{print}' *_youtube_subscribers.csv > merged/merged_youtube_subscribers.csv
